// All 48 WC 2026 teams with condition scores and metadata
export const TEAMS = [
  { id: 'MEX', name: 'Mexico',             group: 'A', flag: '🇲🇽', heat:88, pitch:75, altitude:92, travel:80, crowd:85, schedule:72, confederation:'CONCACAF', fifaRank:16, insight:'Home comforts dominate — unmatched altitude and heat resilience. The Azteca crowd is the 49th player.' },
  { id: 'RSA', name: 'South Africa',        group: 'A', flag: '🇿🇦', heat:85, pitch:60, altitude:78, travel:68, crowd:72, schedule:65, confederation:'CAF',      fifaRank:62, insight:'Strong heat tolerance from PSL conditions. Pitch quality is the main vulnerability.' },
  { id: 'KOR', name: 'South Korea',         group: 'A', flag: '🇰🇷', heat:65, pitch:80, altitude:58, travel:55, crowd:82, schedule:88, confederation:'AFC',      fifaRank:23, insight:'K-League discipline shines in schedule management. Long Asia travel is a real disadvantage.' },
  { id: 'CZE', name: 'Czechia',             group: 'A', flag: '🇨🇿', heat:52, pitch:82, altitude:55, travel:70, crowd:68, schedule:74, confederation:'UEFA',     fifaRank:37, insight:'European pitch comfort but will feel the NA heat and altitude hard.' },
  { id: 'CAN', name: 'Canada',              group: 'B', flag: '🇨🇦', heat:48, pitch:72, altitude:60, travel:82, crowd:65, schedule:70, confederation:'CONCACAF', fifaRank:47, insight:'Host advantage on travel. Cold-climate side will struggle with summer heat in warm US venues.' },
  { id: 'BIH', name: 'Bosnia-Herzegovina', group: 'B', flag: '🇧🇦', heat:62, pitch:70, altitude:66, travel:72, crowd:74, schedule:66, confederation:'UEFA',     fifaRank:64, insight:'Per SantiSignals: heaviest group-stage travel burden in the field — nearly 5,000 km across venues.' },
  { id: 'QAT', name: 'Qatar',               group: 'B', flag: '🇶🇦', heat:94, pitch:78, altitude:55, travel:76, crowd:60, schedule:62, confederation:'AFC',      fifaRank:58, insight:'2022 hosts carry the highest heat score in the tournament. Crowd atmosphere will be unfamiliar away.' },
  { id: 'SUI', name: 'Switzerland',         group: 'B', flag: '🇨🇭', heat:58, pitch:84, altitude:82, travel:78, crowd:70, schedule:80, confederation:'UEFA',     fifaRank:20, insight:'Alpine roots make Switzerland uniquely altitude-resistant. Deep squad, excellent rotation.' },
  { id: 'BRA', name: 'Brazil',              group: 'C', flag: '🇧🇷', heat:92, pitch:72, altitude:80, travel:78, crowd:90, schedule:76, confederation:'CONMEBOL', fifaRank:5,  insight:'South American powerhouse — elite heat and crowd resilience. The Seleção owns any stadium.' },
  { id: 'MAR', name: 'Morocco',             group: 'C', flag: '🇲🇦', heat:84, pitch:68, altitude:75, travel:72, crowd:80, schedule:70, confederation:'CAF',      fifaRank:14, insight:'2022 semi-finalists with proven tournament toughness. North African heat is a genuine asset.' },
  { id: 'HAI', name: 'Haiti',               group: 'C', flag: '🇭🇹', heat:87, pitch:52, altitude:58, travel:62, crowd:68, schedule:55, confederation:'CONCACAF', fifaRank:83, insight:'Excellent heat tolerance from Caribbean background. Pitch and squad depth are real concerns.' },
  { id: 'SCO', name: 'Scotland',            group: 'C', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', heat:40, pitch:82, altitude:45, travel:72, crowd:78, schedule:72, confederation:'UEFA',     fifaRank:39, insight:'Premium pitch comfort but heat is the single biggest threat — Dallas in June is brutal.' },
  { id: 'USA', name: 'USA',                 group: 'D', flag: '🇺🇸', heat:72, pitch:80, altitude:68, travel:88, crowd:80, schedule:82, confederation:'CONCACAF', fifaRank:13, insight:'Host advantage is massive on travel. The USMNT has the crowd and the schedule on their side.' },
  { id: 'PAR', name: 'Paraguay',            group: 'D', flag: '🇵🇾', heat:85, pitch:62, altitude:76, travel:70, crowd:72, schedule:64, confederation:'CONMEBOL', fifaRank:61, insight:'South American heat and altitude experience. Thin squad depth hurts in congested fixtures.' },
  { id: 'AUS', name: 'Australia',           group: 'D', flag: '🇦🇺', heat:78, pitch:74, altitude:62, travel:58, crowd:70, schedule:74, confederation:'AFC',      fifaRank:24, insight:'Worst travel burden among non-Asian sides. Heat-tolerant from A-League summer football.' },
  { id: 'TUR', name: 'Türkiye',             group: 'D', flag: '🇹🇷', heat:74, pitch:76, altitude:68, travel:72, crowd:80, schedule:76, confederation:'UEFA',     fifaRank:26, insight:'Süper Lig experience across varied conditions. Heat-competent from Mediterranean summers.' },
  { id: 'GER', name: 'Germany',             group: 'E', flag: '🇩🇪', heat:56, pitch:90, altitude:58, travel:74, crowd:82, schedule:90, confederation:'UEFA',     fifaRank:12, insight:'Bundesliga depth means extraordinary squad rotation. Pitch is their territory. Heat is a risk.' },
  { id: 'CUW', name: 'Curaçao',             group: 'E', flag: '🇨🇼', heat:90, pitch:58, altitude:52, travel:66, crowd:62, schedule:58, confederation:'CONCACAF', fifaRank:82, insight:'Smallest nation to qualify. Caribbean heat resilience is genuine and top-tier.' },
  { id: 'CIV', name: "Côte d'Ivoire",       group: 'E', flag: '🇨🇮', heat:88, pitch:62, altitude:68, travel:70, crowd:76, schedule:64, confederation:'CAF',      fifaRank:15, insight:'West African heat specialists with Serie A and Ligue 1 pedigree.' },
  { id: 'ECU', name: 'Ecuador',             group: 'E', flag: '🇪🇨', heat:78, pitch:65, altitude:88, travel:72, crowd:70, schedule:68, confederation:'CONMEBOL', fifaRank:33, insight:'Quito is one of the highest capitals — altitude is their superpower. Brutal combined burden per SantiSignals.' },
  { id: 'NED', name: 'Netherlands',         group: 'F', flag: '🇳🇱', heat:52, pitch:90, altitude:52, travel:76, crowd:78, schedule:86, confederation:'UEFA',     fifaRank:7,  insight:'Eredivisie + PL quality gives elite pitch comfort. Deep squad handles schedule brilliantly.' },
  { id: 'JPN', name: 'Japan',               group: 'F', flag: '🇯🇵', heat:76, pitch:88, altitude:60, travel:52, crowd:85, schedule:90, confederation:'AFC',      fifaRank:18, insight:'J-League demands exceptional discipline. Tokyo summers prep them for heat. Tough travel.' },
  { id: 'SWE', name: 'Sweden',              group: 'F', flag: '🇸🇪', heat:46, pitch:84, altitude:52, travel:74, crowd:72, schedule:80, confederation:'UEFA',     fifaRank:25, insight:'Allsvenskan quality with strong European standards. Heat is the standout risk.' },
  { id: 'TUN', name: 'Tunisia',             group: 'F', flag: '🇹🇳', heat:82, pitch:65, altitude:60, travel:68, crowd:70, schedule:64, confederation:'CAF',      fifaRank:34, insight:'North African heat resilience is a real asset. Squad depth limits schedule tolerance.' },
  { id: 'BEL', name: 'Belgium',             group: 'G', flag: '🇧🇪', heat:50, pitch:88, altitude:52, travel:74, crowd:80, schedule:84, confederation:'UEFA',     fifaRank:8,  insight:'Golden Generation sunset era but deep European pedigree. Premium pitches are home territory.' },
  { id: 'EGY', name: 'Egypt',               group: 'G', flag: '🇪🇬', heat:86, pitch:66, altitude:62, travel:70, crowd:82, schedule:68, confederation:'CAF',      fifaRank:43, insight:'North African heat is deeply familiar. Salah\'s influence on crowd intensity is enormous.' },
  { id: 'IRN', name: 'Iran',                group: 'G', flag: '🇮🇷', heat:80, pitch:66, altitude:72, travel:68, crowd:76, schedule:66, confederation:'AFC',      fifaRank:22, insight:'Persepolis-standard heat. Late training base change (Mexico→US) adds disruption per ESPN.' },
  { id: 'NZL', name: 'New Zealand',         group: 'G', flag: '🇳🇿', heat:62, pitch:70, altitude:58, travel:48, crowd:60, schedule:68, confederation:'OFC',      fifaRank:96, insight:'Worst travel score in the field — Pacific crossing is enormous. OFC background limits exposure.' },
  { id: 'ESP', name: 'Spain',               group: 'H', flag: '🇪🇸', heat:72, pitch:90, altitude:65, travel:76, crowd:88, schedule:90, confederation:'UEFA',     fifaRank:1,  insight:'Per SantiSignals: coolest group in the field. Two games under Atlanta roof. World champions.' },
  { id: 'CPV', name: 'Cabo Verde',          group: 'H', flag: '🇨🇻', heat:88, pitch:55, altitude:62, travel:64, crowd:68, schedule:58, confederation:'CAF',      fifaRank:75, insight:'Atlantic island heat specialists. Pitch quality is the clearest limitation.' },
  { id: 'KSA', name: 'Saudi Arabia',        group: 'H', flag: '🇸🇦', heat:90, pitch:72, altitude:60, travel:72, crowd:68, schedule:64, confederation:'AFC',      fifaRank:56, insight:'Roshn Saudi League builds genuine heat tolerance. Pro League investment raised pitch quality.' },
  { id: 'URU', name: 'Uruguay',             group: 'H', flag: '🇺🇾', heat:70, pitch:74, altitude:72, travel:74, crowd:78, schedule:72, confederation:'CONMEBOL', fifaRank:16, insight:'SantiSignals flags recovery risk: above-average burden + one of the oldest squads in the tournament.' },
  { id: 'FRA', name: 'France',              group: 'I', flag: '🇫🇷', heat:64, pitch:88, altitude:58, travel:76, crowd:86, schedule:88, confederation:'UEFA',     fifaRank:3,  insight:'Per SantiSignals: heat with minimal travel — whole group in the Northeast corridor. Elite depth.' },
  { id: 'SEN', name: 'Senegal',             group: 'I', flag: '🇸🇳', heat:86, pitch:62, altitude:66, travel:66, crowd:76, schedule:64, confederation:'CAF',      fifaRank:20, insight:'AFCON-hardened heat specialists. European league experience elevates pitch comfort significantly.' },
  { id: 'IRQ', name: 'Iraq',                group: 'I', flag: '🇮🇶', heat:92, pitch:60, altitude:62, travel:66, crowd:72, schedule:60, confederation:'AFC',      fifaRank:63, insight:'Among the most heat-adapted squads in the field — Baghdad summers are extreme preparation.' },
  { id: 'NOR', name: 'Norway',              group: 'I', flag: '🇳🇴', heat:44, pitch:78, altitude:50, travel:72, crowd:70, schedule:78, confederation:'UEFA',     fifaRank:28, insight:'Haaland\'s Norway boasts PL quality. Heat is the single biggest concern in the tournament.' },
  { id: 'ARG', name: 'Argentina',           group: 'J', flag: '🇦🇷', heat:74, pitch:76, altitude:80, travel:74, crowd:92, schedule:78, confederation:'CONMEBOL', fifaRank:2,  insight:'Per SantiSignals: 48th in burden — softest draw in the tournament. Dallas AC, short hops.' },
  { id: 'ALG', name: 'Algeria',             group: 'J', flag: '🇩🇿', heat:84, pitch:64, altitude:70, travel:70, crowd:74, schedule:64, confederation:'CAF',      fifaRank:40, insight:'Per SantiSignals: 2nd hardest burden at 92/100 — near-identical punishment to Bosnia. Underreported.' },
  { id: 'AUT', name: 'Austria',             group: 'J', flag: '🇦🇹', heat:54, pitch:84, altitude:65, travel:72, crowd:70, schedule:76, confederation:'UEFA',     fifaRank:27, insight:'Bundesliga-level pitch comfort. Alpine background offers mild altitude tolerance.' },
  { id: 'JOR', name: 'Jordan',              group: 'J', flag: '🇯🇴', heat:86, pitch:62, altitude:68, travel:68, crowd:68, schedule:60, confederation:'AFC',      fifaRank:71, insight:'Middle East heat environment is excellent prep for warm US venues. First World Cup.' },
  { id: 'POR', name: 'Portugal',            group: 'K', flag: '🇵🇹', heat:72, pitch:84, altitude:62, travel:74, crowd:86, schedule:86, confederation:'UEFA',     fifaRank:6,  insight:'Ronaldo\'s final chapter. Primeira Liga + European pedigree. Always galvanized under pressure.' },
  { id: 'COD', name: 'Congo DR',            group: 'K', flag: '🇨🇩', heat:86, pitch:55, altitude:70, travel:60, crowd:68, schedule:58, confederation:'CAF',      fifaRank:55, insight:'Equatorial heat specialists. Linafoot pitch quality is among the lowest in the tournament.' },
  { id: 'UZB', name: 'Uzbekistan',          group: 'K', flag: '🇺🇿', heat:80, pitch:68, altitude:74, travel:62, crowd:64, schedule:64, confederation:'AFC',      fifaRank:50, insight:'Central Asian conditions with extreme temperature variation. Surprise qualifiers with real resilience.' },
  { id: 'COL', name: 'Colombia',            group: 'K', flag: '🇨🇴', heat:82, pitch:68, altitude:82, travel:72, crowd:80, schedule:70, confederation:'CONMEBOL', fifaRank:13, insight:'Bogotá at 2,600m gives elite altitude conditioning. Copa Libertadores heat rounds out the profile.' },
  { id: 'ENG', name: 'England',             group: 'L', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', heat:50, pitch:88, altitude:50, travel:74, crowd:84, schedule:88, confederation:'UEFA',     fifaRank:4,  insight:'Per SantiSignals: 8th hardest burden — 2,767 km across warm venues. Worst among top favorites.' },
  { id: 'CRO', name: 'Croatia',             group: 'L', flag: '🇭🇷', heat:68, pitch:80, altitude:62, travel:72, crowd:80, schedule:78, confederation:'UEFA',     fifaRank:10, insight:'Adriatic coast heat is useful prep. Veteran Euro know-how. Aging squad raises recovery questions.' },
  { id: 'GHA', name: 'Ghana',               group: 'L', flag: '🇬🇭', heat:86, pitch:62, altitude:66, travel:68, crowd:76, schedule:64, confederation:'CAF',      fifaRank:57, insight:'West African heat specialists. PL diaspora elevates technical quality. Schedule depth is thin.' },
  { id: 'PAN', name: 'Panama',              group: 'L', flag: '🇵🇦', heat:88, pitch:58, altitude:62, travel:72, crowd:70, schedule:60, confederation:'CONCACAF', fifaRank:49, insight:'Panama City humidity is one of the most demanding prep environments in the Americas.' },
]

// All group-stage fixtures with confirmed venues
export const FIXTURES = [
  // Group A
  { id:'A1', group:'A', home:'MEX', away:'RSA', venue:'Estadio Azteca',     city:'Mexico City',  date:'2026-06-11', time:'15:00', roofed:false, altitude:2240 },
  { id:'A2', group:'A', home:'KOR', away:'CZE', venue:'Estadio Akron',      city:'Guadalajara',  date:'2026-06-11', time:'22:00', roofed:false, altitude:1566 },
  { id:'A3', group:'A', home:'CZE', away:'RSA', venue:'Mercedes-Benz Stadium', city:'Atlanta',  date:'2026-06-18', time:'12:00', roofed:true,  altitude:287  },
  { id:'A4', group:'A', home:'MEX', away:'KOR', venue:'Estadio Akron',      city:'Guadalajara',  date:'2026-06-18', time:'21:00', roofed:false, altitude:1566 },
  { id:'A5', group:'A', home:'CZE', away:'MEX', venue:'Estadio Azteca',     city:'Mexico City',  date:'2026-06-24', time:'21:00', roofed:false, altitude:2240 },
  { id:'A6', group:'A', home:'RSA', away:'KOR', venue:'Estadio BBVA',       city:'Monterrey',    date:'2026-06-24', time:'21:00', roofed:false, altitude:537  },
  // Group B
  { id:'B1', group:'B', home:'CAN', away:'BIH', venue:'BMO Field',          city:'Toronto',      date:'2026-06-12', time:'15:00', roofed:false, altitude:76   },
  { id:'B2', group:'B', home:'QAT', away:'SUI', venue:"Levi's Stadium",     city:'Santa Clara',  date:'2026-06-13', time:'15:00', roofed:false, altitude:18   },
  { id:'B3', group:'B', home:'SUI', away:'BIH', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-18', time:'15:00', roofed:true,  altitude:89   },
  { id:'B4', group:'B', home:'CAN', away:'QAT', venue:'BC Place',           city:'Vancouver',    date:'2026-06-18', time:'18:00', roofed:true,  altitude:5    },
  { id:'B5', group:'B', home:'BIH', away:'QAT', venue:'BC Place',           city:'Vancouver',    date:'2026-06-24', time:'15:00', roofed:true,  altitude:5    },
  { id:'B6', group:'B', home:'SUI', away:'CAN', venue:'BMO Field',          city:'Toronto',      date:'2026-06-24', time:'15:00', roofed:false, altitude:76   },
  // Group C
  { id:'C1', group:'C', home:'HAI', away:'SCO', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-14', time:'02:00', roofed:false, altitude:24   },
  { id:'C2', group:'C', home:'BRA', away:'MAR', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-15', time:'21:00', roofed:true,  altitude:186  },
  { id:'C3', group:'C', home:'SCO', away:'MAR', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-19', time:'23:00', roofed:false, altitude:24   },
  { id:'C4', group:'C', home:'BRA', away:'HAI', venue:'Hard Rock Stadium',  city:'Miami',        date:'2026-06-20', time:'21:00', roofed:false, altitude:2    },
  { id:'C5', group:'C', home:'SCO', away:'BRA', venue:'Hard Rock Stadium',  city:'Miami',        date:'2026-06-24', time:'23:00', roofed:false, altitude:2    },
  { id:'C6', group:'C', home:'MAR', away:'HAI', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-24', time:'23:00', roofed:true,  altitude:186  },
  // Group D
  { id:'D1', group:'D', home:'USA', away:'PAR', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-12', time:'21:00', roofed:true,  altitude:89   },
  { id:'D2', group:'D', home:'AUS', away:'TUR', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-13', time:'21:00', roofed:false, altitude:4    },
  { id:'D3', group:'D', home:'PAR', away:'TUR', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-19', time:'18:00', roofed:true,  altitude:89   },
  { id:'D4', group:'D', home:'USA', away:'AUS', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-20', time:'18:00', roofed:false, altitude:4    },
  { id:'D5', group:'D', home:'TUR', away:'USA', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-25', time:'21:00', roofed:false, altitude:4    },
  { id:'D6', group:'D', home:'PAR', away:'AUS', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-25', time:'21:00', roofed:true,  altitude:89   },
  // Group E
  { id:'E1', group:'E', home:'GER', away:'CUW', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-12', time:'18:00', roofed:false, altitude:2    },
  { id:'E2', group:'E', home:'CIV', away:'ECU', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-13', time:'18:00', roofed:true,  altitude:186  },
  { id:'E3', group:'E', home:'ECU', away:'CUW', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-19', time:'15:00', roofed:false, altitude:2    },
  { id:'E4', group:'E', home:'GER', away:'CIV', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-20', time:'15:00', roofed:true,  altitude:186  },
  { id:'E5', group:'E', home:'CUW', away:'CIV', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-25', time:'18:00', roofed:true,  altitude:186  },
  { id:'E6', group:'E', home:'ECU', away:'GER', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-25', time:'18:00', roofed:false, altitude:2    },
  // Group F
  { id:'F1', group:'F', home:'NED', away:'TUN', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-12', time:'15:00', roofed:false, altitude:4    },
  { id:'F2', group:'F', home:'JPN', away:'SWE', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-14', time:'18:00', roofed:false, altitude:24   },
  { id:'F3', group:'F', home:'SWE', away:'TUN', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-19', time:'18:00', roofed:false, altitude:24   },
  { id:'F4', group:'F', home:'NED', away:'JPN', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-20', time:'21:00', roofed:false, altitude:4    },
  { id:'F5', group:'F', home:'TUN', away:'JPN', venue:'Lumen Field',        city:'Seattle',      date:'2026-06-25', time:'15:00', roofed:false, altitude:4    },
  { id:'F6', group:'F', home:'SWE', away:'NED', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-25', time:'15:00', roofed:false, altitude:24   },
  // Group G
  { id:'G1', group:'G', home:'BEL', away:'EGY', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-13', time:'21:00', roofed:true,  altitude:186  },
  { id:'G2', group:'G', home:'IRN', away:'NZL', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-14', time:'21:00', roofed:false, altitude:24   },
  { id:'G3', group:'G', home:'EGY', away:'NZL', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-20', time:'12:00', roofed:true,  altitude:186  },
  { id:'G4', group:'G', home:'BEL', away:'IRN', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-21', time:'12:00', roofed:false, altitude:24   },
  { id:'G5', group:'G', home:'NZL', away:'BEL', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-26', time:'21:00', roofed:true,  altitude:186  },
  { id:'G6', group:'G', home:'EGY', away:'IRN', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-26', time:'21:00', roofed:false, altitude:24   },
  // Group H
  { id:'H1', group:'H', home:'ESP', away:'CPV', venue:'Mercedes-Benz Stadium', city:'Atlanta',  date:'2026-06-15', time:'18:00', roofed:true,  altitude:287  },
  { id:'H2', group:'H', home:'KSA', away:'URU', venue:'Hard Rock Stadium',  city:'Miami',        date:'2026-06-15', time:'15:00', roofed:false, altitude:2    },
  { id:'H3', group:'H', home:'CPV', away:'URU', venue:'Mercedes-Benz Stadium', city:'Atlanta',  date:'2026-06-21', time:'15:00', roofed:true,  altitude:287  },
  { id:'H4', group:'H', home:'ESP', away:'KSA', venue:'Mercedes-Benz Stadium', city:'Atlanta',  date:'2026-06-21', time:'18:00', roofed:true,  altitude:287  },
  { id:'H5', group:'H', home:'URU', away:'ESP', venue:'Estadio Akron',      city:'Guadalajara',  date:'2026-06-26', time:'02:00', roofed:false, altitude:1566 },
  { id:'H6', group:'H', home:'CPV', away:'KSA', venue:'Hard Rock Stadium',  city:'Miami',        date:'2026-06-26', time:'02:00', roofed:false, altitude:2    },
  // Group I
  { id:'I1', group:'I', home:'FRA', away:'SEN', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-14', time:'21:00', roofed:false, altitude:2    },
  { id:'I2', group:'I', home:'IRQ', away:'NOR', venue:'Lincoln Financial',  city:'Philadelphia', date:'2026-06-15', time:'21:00', roofed:false, altitude:11   },
  { id:'I3', group:'I', home:'SEN', away:'NOR', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-21', time:'21:00', roofed:false, altitude:2    },
  { id:'I4', group:'I', home:'FRA', away:'IRQ', venue:'Lincoln Financial',  city:'Philadelphia', date:'2026-06-22', time:'21:00', roofed:false, altitude:11   },
  { id:'I5', group:'I', home:'NOR', away:'FRA', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-27', time:'21:00', roofed:false, altitude:24   },
  { id:'I6', group:'I', home:'SEN', away:'IRQ', venue:'Lincoln Financial',  city:'Philadelphia', date:'2026-06-27', time:'21:00', roofed:false, altitude:11   },
  // Group J
  { id:'J1', group:'J', home:'ARG', away:'ALG', venue:'Arrowhead Stadium',  city:'Kansas City',  date:'2026-06-16', time:'21:00', roofed:false, altitude:290  },
  { id:'J2', group:'J', home:'AUT', away:'JOR', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-17', time:'19:00', roofed:true,  altitude:186  },
  { id:'J3', group:'J', home:'ALG', away:'JOR', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-22', time:'15:00', roofed:true,  altitude:186  },
  { id:'J4', group:'J', home:'ARG', away:'AUT', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-23', time:'19:00', roofed:true,  altitude:186  },
  { id:'J5', group:'J', home:'JOR', away:'ARG', venue:'Arrowhead Stadium',  city:'Kansas City',  date:'2026-06-28', time:'21:00', roofed:false, altitude:290  },
  { id:'J6', group:'J', home:'ALG', away:'AUT', venue:'Arrowhead Stadium',  city:'Kansas City',  date:'2026-06-28', time:'21:00', roofed:false, altitude:290  },
  // Group K
  { id:'K1', group:'K', home:'POR', away:'COD', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-16', time:'18:00', roofed:true,  altitude:89   },
  { id:'K2', group:'K', home:'UZB', away:'COL', venue:'Rose Bowl',          city:'Los Angeles',  date:'2026-06-17', time:'18:00', roofed:false, altitude:258  },
  { id:'K3', group:'K', home:'COD', away:'COL', venue:'Rose Bowl',          city:'Los Angeles',  date:'2026-06-22', time:'18:00', roofed:false, altitude:258  },
  { id:'K4', group:'K', home:'POR', away:'UZB', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-23', time:'15:00', roofed:true,  altitude:89   },
  { id:'K5', group:'K', home:'COL', away:'POR', venue:'Rose Bowl',          city:'Los Angeles',  date:'2026-06-28', time:'18:00', roofed:false, altitude:258  },
  { id:'K6', group:'K', home:'COD', away:'UZB', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-28', time:'18:00', roofed:true,  altitude:89   },
  // Group L
  { id:'L1', group:'L', home:'ENG', away:'CRO', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-17', time:'22:00', roofed:true,  altitude:186  },
  { id:'L2', group:'L', home:'GHA', away:'PAN', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-18', time:'21:00', roofed:true,  altitude:89   },
  { id:'L3', group:'L', home:'ENG', away:'GHA', venue:'Gillette Stadium',   city:'Boston',       date:'2026-06-23', time:'22:00', roofed:false, altitude:24   },
  { id:'L4', group:'L', home:'CRO', away:'PAN', venue:'SoFi Stadium',       city:'Los Angeles',  date:'2026-06-24', time:'18:00', roofed:true,  altitude:89   },
  { id:'L5', group:'L', home:'ENG', away:'PAN', venue:'MetLife Stadium',    city:'New York',     date:'2026-06-27', time:'23:00', roofed:false, altitude:2    },
  { id:'L6', group:'L', home:'CRO', away:'GHA', venue:'AT&T Stadium',       city:'Dallas',       date:'2026-06-27', time:'21:00', roofed:true,  altitude:186  },
]

export const CONDITIONS = [
  { key: 'heat',     label: 'Heat & humidity', short: 'Heat',  icon: '☀' },
  { key: 'pitch',    label: 'Pitch quality',   short: 'Pitch', icon: '🏟' },
  { key: 'altitude', label: 'Altitude',        short: 'Alt',   icon: '⛰' },
  { key: 'travel',   label: 'Travel & jet lag',short: 'Travel',icon: '✈' },
  { key: 'crowd',    label: 'Crowd pressure',  short: 'Crowd', icon: '👥' },
  { key: 'schedule', label: 'Fixture load',    short: 'Sched', icon: '📅' },
]

export const GROUPS = ['A','B','C','D','E','F','G','H','I','J','K','L']
