export const TEAMS = [
  { id:'MEX', name:'Mexico',             group:'A', flag:'🇲🇽', heat:89,  pitch:61,  altitude:100, travel:80,  crowd:78,  schedule:49,  confederation:'CONCACAF', fifaRank:15, insight:'Home comforts dominate — unmatched altitude and heat resilience. The Azteca crowd is the 49th player.' },
  { id:'RSA', name:'South Africa',        group:'A', flag:'🇿🇦', heat:84,  pitch:22,  altitude:71,  travel:50,  crowd:38,  schedule:29,  confederation:'CAF',      fifaRank:61, insight:'Strong heat tolerance from PSL conditions. Pitch quality is the main vulnerability.' },
  { id:'KOR', name:'South Korea',         group:'A', flag:'🇰🇷', heat:47,  pitch:74,  altitude:28,  travel:18,  crowd:69,  schedule:94,  confederation:'AFC',      fifaRank:22, insight:'K-League discipline shines in schedule management. Long Asia travel is a real disadvantage.' },
  { id:'CZE', name:'Czechia',             group:'A', flag:'🇨🇿', heat:23,  pitch:79,  altitude:22,  travel:55,  crowd:26,  schedule:55,  confederation:'UEFA',     fifaRank:44, insight:'European pitch comfort but will feel the NA heat and altitude hard.' },
  { id:'CAN', name:'Canada',              group:'B', flag:'🇨🇦', heat:16,  pitch:53,  altitude:33,  travel:85,  crowd:16,  schedule:43,  confederation:'CONCACAF', fifaRank:27, insight:'Host advantage on travel. Cold-climate side will struggle with summer heat in warm US venues.' },
  { id:'BIH', name:'Bosnia-Herzegovina', group:'B', flag:'🇧🇦', heat:41,  pitch:48,  altitude:45,  travel:60,  crowd:44,  schedule:32,  confederation:'UEFA',     fifaRank:71, insight:'Per SantiSignals: heaviest group-stage travel burden in the field — nearly 5,000 km across venues.' },
  { id:'QAT', name:'Qatar',               group:'B', flag:'🇶🇦', heat:100, pitch:69,  altitude:22,  travel:70,  crowd:1,   schedule:21,  confederation:'AFC',      fifaRank:51, insight:'2022 hosts carry the highest heat score in the tournament. Crowd atmosphere will be unfamiliar away.' },
  { id:'SUI', name:'Switzerland',         group:'B', flag:'🇨🇭', heat:34,  pitch:84,  altitude:79,  travel:75,  crowd:32,  schedule:72,  confederation:'UEFA',     fifaRank:17, insight:'Alpine roots make Switzerland uniquely altitude-resistant. Deep squad, excellent rotation.' },
  { id:'BRA', name:'Brazil',              group:'C', flag:'🇧🇷', heat:96,  pitch:53,  altitude:75,  travel:75,  crowd:94,  schedule:60,  confederation:'CONMEBOL', fifaRank:5,  insight:'South American powerhouse — elite heat and crowd resilience. The Seleção owns any stadium.' },
  { id:'MAR', name:'Morocco',             group:'C', flag:'🇲🇦', heat:82,  pitch:43,  altitude:64,  travel:60,  crowd:63,  schedule:43,  confederation:'CAF',      fifaRank:11, insight:'2022 semi-finalists with proven tournament toughness. North African heat is a genuine asset.' },
  { id:'HAI', name:'Haiti',               group:'C', flag:'🇭🇹', heat:87,  pitch:1,   altitude:28,  travel:36,  crowd:26,  schedule:1,   confederation:'CONCACAF', fifaRank:84, insight:'Excellent heat tolerance from Caribbean background. Pitch and squad depth are real concerns.' },
  { id:'SCO', name:'Scotland',            group:'C', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', heat:1,   pitch:79,  altitude:1,   travel:60,  crowd:57,  schedule:49,  confederation:'UEFA',     fifaRank:36, insight:'Premium pitch comfort but heat is the single biggest threat — Dallas in June is brutal.' },
  { id:'USA', name:'USA',                 group:'D', flag:'🇺🇸', heat:60,  pitch:74,  altitude:49,  travel:100, crowd:63,  schedule:77,  confederation:'CONCACAF', fifaRank:13, insight:'Host advantage is massive on travel. The USMNT has the crowd and the schedule on their side.' },
  { id:'PAR', name:'Paraguay',            group:'D', flag:'🇵🇾', heat:84,  pitch:27,  altitude:66,  travel:55,  crowd:38,  schedule:26,  confederation:'CONMEBOL', fifaRank:61, insight:'South American heat and altitude experience. Thin squad depth hurts in congested fixtures.' },
  { id:'AUS', name:'Australia',           group:'D', flag:'🇦🇺', heat:71,  pitch:58,  altitude:37,  travel:26,  crowd:32,  schedule:55,  confederation:'AFC',      fifaRank:24, insight:'Worst travel burden among non-Asian sides. Heat-tolerant from A-League summer football.' },
  { id:'TUR', name:'Türkiye',             group:'D', flag:'🇹🇷', heat:63,  pitch:64,  altitude:49,  travel:60,  crowd:63,  schedule:60,  confederation:'UEFA',     fifaRank:26, insight:'Süper Lig experience across varied conditions. Heat-competent from Mediterranean summers.' },
  { id:'GER', name:'Germany',             group:'E', flag:'🇩🇪', heat:30,  pitch:100, altitude:28,  travel:65,  crowd:69,  schedule:100, confederation:'UEFA',     fifaRank:12, insight:'Bundesliga depth means extraordinary squad rotation. Pitch is their territory. Heat is a risk.' },
  { id:'CUW', name:'Curaçao',             group:'E', flag:'🇨🇼', heat:93,  pitch:17,  altitude:16,  travel:46,  crowd:7,   schedule:9,   confederation:'CONCACAF', fifaRank:82, insight:'Smallest nation to qualify. Caribbean heat resilience is genuine and top-tier.' },
  { id:'CIV', name:"Côte d'Ivoire",       group:'E', flag:'🇨🇮', heat:89,  pitch:27,  altitude:49,  travel:55,  crowd:50,  schedule:26,  confederation:'CAF',      fifaRank:15, insight:'West African heat specialists with Serie A and Ligue 1 pedigree.' },
  { id:'ECU', name:'Ecuador',             group:'E', flag:'🇪🇨', heat:71,  pitch:35,  altitude:92,  travel:60,  crowd:32,  schedule:38,  confederation:'CONMEBOL', fifaRank:33, insight:'Quito is one of the highest capitals — altitude is their superpower.' },
  { id:'NED', name:'Netherlands',         group:'F', flag:'🇳🇱', heat:23,  pitch:100, altitude:16,  travel:70,  crowd:57,  schedule:89,  confederation:'UEFA',     fifaRank:7,  insight:'Eredivisie + PL quality gives elite pitch comfort. Deep squad handles schedule brilliantly.' },
  { id:'JPN', name:'Japan',               group:'F', flag:'🇯🇵', heat:67,  pitch:95,  altitude:33,  travel:11,  crowd:78,  schedule:100, confederation:'AFC',      fifaRank:18, insight:'J-League demands exceptional discipline. Tokyo summers prep them for heat. Tough travel.' },
  { id:'SWE', name:'Sweden',              group:'F', flag:'🇸🇪', heat:12,  pitch:84,  altitude:16,  travel:65,  crowd:38,  schedule:72,  confederation:'UEFA',     fifaRank:25, insight:'Allsvenskan quality with strong European standards. Heat is the standout risk.' },
  { id:'TUN', name:'Tunisia',             group:'F', flag:'🇹🇳', heat:78,  pitch:35,  altitude:33,  travel:50,  crowd:32,  schedule:26,  confederation:'CAF',      fifaRank:34, insight:'North African heat resilience is a real asset. Squad depth limits schedule tolerance.' },
  { id:'BEL', name:'Belgium',             group:'G', flag:'🇧🇪', heat:19,  pitch:95,  altitude:16,  travel:65,  crowd:63,  schedule:83,  confederation:'UEFA',     fifaRank:8,  insight:'Golden Generation sunset era but deep European pedigree. Premium pitches are home territory.' },
  { id:'EGY', name:'Egypt',               group:'G', flag:'🇪🇬', heat:85,  pitch:37,  altitude:37,  travel:55,  crowd:69,  schedule:38,  confederation:'CAF',      fifaRank:43, insight:'North African heat is deeply familiar. Salah\'s influence on crowd intensity is enormous.' },
  { id:'IRN', name:'Iran',                group:'G', flag:'🇮🇷', heat:74,  pitch:37,  altitude:58,  travel:50,  crowd:50,  schedule:32,  confederation:'AFC',      fifaRank:22, insight:'Persepolis-standard heat. Late training base change adds disruption.' },
  { id:'NZL', name:'New Zealand',         group:'G', flag:'🇳🇿', heat:41,  pitch:48,  altitude:28,  travel:1,   crowd:1,   schedule:38,  confederation:'OFC',      fifaRank:96, insight:'Worst travel score in the field — Pacific crossing is enormous.' },
  { id:'ESP', name:'Spain',               group:'H', flag:'🇪🇸', heat:60,  pitch:100, altitude:43,  travel:70,  crowd:88,  schedule:100, confederation:'UEFA',     fifaRank:1,  insight:'Two games under Atlanta roof. World champions with unmatched squad depth.' },
  { id:'CPV', name:'Cabo Verde',          group:'H', flag:'🇨🇻', heat:89,  pitch:9,   altitude:37,  travel:41,  crowd:26,  schedule:9,   confederation:'CAF',      fifaRank:75, insight:'Atlantic island heat specialists. Pitch quality is the clearest limitation.' },
  { id:'KSA', name:'Saudi Arabia',        group:'H', flag:'🇸🇦', heat:93,  pitch:53,  altitude:33,  travel:60,  crowd:26,  schedule:26,  confederation:'AFC',      fifaRank:56, insight:'Roshn Saudi League builds genuine heat tolerance. Pro League investment raised pitch quality.' },
  { id:'URU', name:'Uruguay',             group:'H', flag:'🇺🇾', heat:56,  pitch:58,  altitude:58,  travel:65,  crowd:57,  schedule:49,  confederation:'CONMEBOL', fifaRank:16, insight:'Recovery risk: above-average burden + one of the oldest squads in the tournament.' },
  { id:'FRA', name:'France',              group:'I', flag:'🇫🇷', heat:45,  pitch:95,  altitude:28,  travel:70,  crowd:81,  schedule:94,  confederation:'UEFA',     fifaRank:3,  insight:'Whole group in the Northeast corridor — minimal travel. Elite depth throughout.' },
  { id:'SEN', name:'Senegal',             group:'I', flag:'🇸🇳', heat:85,  pitch:27,  altitude:45,  travel:46,  crowd:50,  schedule:26,  confederation:'CAF',      fifaRank:20, insight:'AFCON-hardened heat specialists. European league experience elevates pitch comfort.' },
  { id:'IRQ', name:'Iraq',                group:'I', flag:'🇮🇶', heat:96,  pitch:22,  altitude:37,  travel:46,  crowd:38,  schedule:15,  confederation:'AFC',      fifaRank:63, insight:'Among the most heat-adapted squads — Baghdad summers are extreme preparation.' },
  { id:'NOR', name:'Norway',              group:'I', flag:'🇳🇴', heat:8,   pitch:69,  altitude:12,  travel:60,  crowd:32,  schedule:66,  confederation:'UEFA',     fifaRank:28, insight:'Haaland\'s Norway boasts PL quality. Heat is the single biggest concern.' },
  { id:'ARG', name:'Argentina',           group:'J', flag:'🇦🇷', heat:63,  pitch:64,  altitude:75,  travel:65,  crowd:100, schedule:66,  confederation:'CONMEBOL', fifaRank:2,  insight:'Softest draw in the tournament. Dallas AC, short hops. Defending champions.' },
  { id:'ALG', name:'Algeria',             group:'J', flag:'🇩🇿', heat:82,  pitch:32,  altitude:54,  travel:55,  crowd:44,  schedule:26,  confederation:'CAF',      fifaRank:40, insight:'2nd hardest burden — near-identical punishment to Bosnia. Underreported threat.' },
  { id:'AUT', name:'Austria',             group:'J', flag:'🇦🇹', heat:27,  pitch:84,  altitude:43,  travel:60,  crowd:32,  schedule:60,  confederation:'UEFA',     fifaRank:27, insight:'Bundesliga-level pitch comfort. Alpine background offers mild altitude tolerance.' },
  { id:'JOR', name:'Jordan',              group:'J', flag:'🇯🇴', heat:85,  pitch:27,  altitude:49,  travel:50,  crowd:26,  schedule:15,  confederation:'AFC',      fifaRank:71, insight:'Middle East heat environment is excellent prep for warm US venues. First World Cup.' },
  { id:'POR', name:'Portugal',            group:'K', flag:'🇵🇹', heat:60,  pitch:84,  altitude:37,  travel:65,  crowd:81,  schedule:89,  confederation:'UEFA',     fifaRank:6,  insight:'Primeira Liga + European pedigree. Always galvanized under pressure.' },
  { id:'COD', name:'Congo DR',            group:'K', flag:'🇨🇩', heat:85,  pitch:9,   altitude:54,  travel:31,  crowd:26,  schedule:9,   confederation:'CAF',      fifaRank:55, insight:'Equatorial heat specialists. Linafoot pitch quality is among the lowest in the tournament.' },
  { id:'UZB', name:'Uzbekistan',          group:'K', flag:'🇺🇿', heat:74,  pitch:43,  altitude:62,  travel:36,  crowd:13,  schedule:26,  confederation:'AFC',      fifaRank:50, insight:'Central Asian conditions with extreme temperature variation. Surprise qualifiers.' },
  { id:'COL', name:'Colombia',            group:'K', flag:'🇨🇴', heat:78,  pitch:43,  altitude:79,  travel:60,  crowd:63,  schedule:43,  confederation:'CONMEBOL', fifaRank:13, insight:'Bogotá at 2,600m gives elite altitude conditioning. Copa Libertadores heat rounds out the profile.' },
  { id:'ENG', name:'England',             group:'L', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', heat:19,  pitch:95,  altitude:12,  travel:65,  crowd:75,  schedule:94,  confederation:'UEFA',     fifaRank:4,  insight:'2,767 km across warm venues — worst burden among top favorites.' },
  { id:'CRO', name:'Croatia',             group:'L', flag:'🇭🇷', heat:52,  pitch:74,  altitude:37,  travel:60,  crowd:63,  schedule:66,  confederation:'UEFA',     fifaRank:10, insight:'Adriatic coast heat is useful prep. Veteran Euro know-how. Aging squad raises recovery questions.' },
  { id:'GHA', name:'Ghana',               group:'L', flag:'🇬🇭', heat:85,  pitch:27,  altitude:45,  travel:50,  crowd:50,  schedule:26,  confederation:'CAF',      fifaRank:57, insight:'West African heat specialists. PL diaspora elevates technical quality.' },
  { id:'PAN', name:'Panama',              group:'L', flag:'🇵🇦', heat:89,  pitch:17,  altitude:37,  travel:60,  crowd:32,  schedule:15,  confederation:'CONCACAF', fifaRank:49, insight:'Panama City humidity is one of the most demanding prep environments in the Americas.' },
]

export const FIXTURES = [
  // GROUP A
  { id:'A1', apiId:1489369, group:'A', home:'MEX', away:'RSA', venue:'Estadio Azteca',        city:'Mexico City',  date:'2026-06-11', time:'14:00', roofed:false, altitude:2240 },
  { id:'A2', apiId:1538999, group:'A', home:'KOR', away:'CZE', venue:'Estadio Akron',         city:'Guadalajara',  date:'2026-06-11', time:'21:00', roofed:false, altitude:1566 },
  { id:'A3', apiId:1539004, group:'A', home:'CZE', away:'RSA', venue:'Mercedes-Benz Stadium', city:'Atlanta',      date:'2026-06-18', time:'12:00', roofed:true,  altitude:287  },
  { id:'A4', apiId:1489388, group:'A', home:'MEX', away:'KOR', venue:'Estadio Akron',         city:'Guadalajara',  date:'2026-06-18', time:'20:00', roofed:false, altitude:1566 },
  { id:'A5', apiId:1539010, group:'A', home:'CZE', away:'MEX', venue:'Estadio Azteca',        city:'Mexico City',  date:'2026-06-24', time:'20:00', roofed:false, altitude:2240 },
  { id:'A6', apiId:1489407, group:'A', home:'RSA', away:'KOR', venue:'Estadio BBVA',          city:'Monterrey',    date:'2026-06-24', time:'20:00', roofed:false, altitude:537  },
  // GROUP B
  { id:'B1', apiId:1539000, group:'B', home:'CAN', away:'BIH', venue:'BMO Field',             city:'Toronto',      date:'2026-06-12', time:'15:00', roofed:false, altitude:76   },
  { id:'B2', apiId:1489373, group:'B', home:'QAT', away:'SUI', venue:"Levi's Stadium",        city:'Santa Clara',  date:'2026-06-13', time:'12:00', roofed:false, altitude:18   },
  { id:'B3', apiId:1539005, group:'B', home:'SUI', away:'BIH', venue:'SoFi Stadium',          city:'Los Angeles',  date:'2026-06-18', time:'12:00', roofed:true,  altitude:89   },
  { id:'B4', apiId:1489387, group:'B', home:'CAN', away:'QAT', venue:'BC Place',              city:'Vancouver',    date:'2026-06-18', time:'15:00', roofed:true,  altitude:5    },
  { id:'B5', apiId:1489408, group:'B', home:'SUI', away:'CAN', venue:'BC Place',              city:'Vancouver',    date:'2026-06-24', time:'12:00', roofed:true,  altitude:5    },
  { id:'B6', apiId:1539009, group:'B', home:'BIH', away:'QAT', venue:'Lumen Field',           city:'Seattle',      date:'2026-06-24', time:'12:00', roofed:false, altitude:4    },
  // GROUP C
  { id:'C1', apiId:1489371, group:'C', home:'BRA', away:'MAR', venue:'MetLife Stadium',       city:'New York',     date:'2026-06-13', time:'18:00', roofed:false, altitude:2    },
  { id:'C2', apiId:1489372, group:'C', home:'HAI', away:'SCO', venue:'Gillette Stadium',      city:'Boston',       date:'2026-06-13', time:'21:00', roofed:false, altitude:24   },
  { id:'C3', apiId:1489390, group:'C', home:'SCO', away:'MAR', venue:'Gillette Stadium',      city:'Boston',       date:'2026-06-19', time:'18:00', roofed:false, altitude:24   },
  { id:'C4', apiId:1489389, group:'C', home:'BRA', away:'HAI', venue:'Lincoln Financial Field',city:'Philadelphia', date:'2026-06-19', time:'20:30', roofed:false, altitude:11   },
  { id:'C5', apiId:1489405, group:'C', home:'MAR', away:'HAI', venue:'Mercedes-Benz Stadium', city:'Atlanta',      date:'2026-06-24', time:'18:00', roofed:true,  altitude:287  },
  { id:'C6', apiId:1489406, group:'C', home:'SCO', away:'BRA', venue:'Hard Rock Stadium',     city:'Miami',        date:'2026-06-24', time:'18:00', roofed:false, altitude:2    },
  // GROUP D
  { id:'D1', apiId:1489370, group:'D', home:'USA', away:'PAR', venue:'SoFi Stadium',          city:'Los Angeles',  date:'2026-06-12', time:'18:00', roofed:true,  altitude:89   },
  { id:'D2', apiId:1539001, group:'D', home:'AUS', away:'TUR', venue:'BC Place',              city:'Vancouver',    date:'2026-06-13', time:'21:00', roofed:true,  altitude:5    },
  { id:'D3', apiId:1489391, group:'D', home:'USA', away:'AUS', venue:'Lumen Field',           city:'Seattle',      date:'2026-06-19', time:'12:00', roofed:false, altitude:4    },
  { id:'D4', apiId:1539006, group:'D', home:'TUR', away:'PAR', venue:"Levi's Stadium",        city:'Santa Clara',  date:'2026-06-19', time:'20:00', roofed:false, altitude:18   },
  { id:'D5', apiId:1539012, group:'D', home:'TUR', away:'USA', venue:'SoFi Stadium',          city:'Los Angeles',  date:'2026-06-25', time:'19:00', roofed:true,  altitude:89   },
  { id:'D6', apiId:1489411, group:'D', home:'PAR', away:'AUS', venue:"Levi's Stadium",        city:'Santa Clara',  date:'2026-06-25', time:'19:00', roofed:false, altitude:18   },
  // GROUP E
  { id:'E1', apiId:1489374, group:'E', home:'GER', away:'CUW', venue:'NRG Stadium',           city:'Houston',      date:'2026-06-14', time:'12:00', roofed:true,  altitude:35   },
  { id:'E2', apiId:1489375, group:'E', home:'CIV', away:'ECU', venue:'Lincoln Financial Field',city:'Philadelphia', date:'2026-06-14', time:'19:00', roofed:false, altitude:11   },
  { id:'E3', apiId:1489393, group:'E', home:'GER', away:'CIV', venue:'BMO Field',             city:'Toronto',      date:'2026-06-20', time:'16:00', roofed:false, altitude:76   },
  { id:'E4', apiId:1489392, group:'E', home:'ECU', away:'CUW', venue:'Arrowhead Stadium',     city:'Kansas City',  date:'2026-06-20', time:'19:00', roofed:false, altitude:290  },
  { id:'E5', apiId:1489410, group:'E', home:'ECU', away:'GER', venue:'MetLife Stadium',       city:'New York',     date:'2026-06-25', time:'16:00', roofed:false, altitude:2    },
  { id:'E6', apiId:1489409, group:'E', home:'CUW', away:'CIV', venue:'Lincoln Financial Field',city:'Philadelphia', date:'2026-06-25', time:'16:00', roofed:false, altitude:11   },
  // GROUP F
  { id:'F1', apiId:1489376, group:'F', home:'NED', away:'JPN', venue:'AT&T Stadium',          city:'Dallas',       date:'2026-06-14', time:'15:00', roofed:true,  altitude:186  },
  { id:'F2', apiId:1539002, group:'F', home:'SWE', away:'TUN', venue:'Estadio BBVA',          city:'Monterrey',    date:'2026-06-14', time:'21:00', roofed:false, altitude:537  },
  { id:'F3', apiId:1539007, group:'F', home:'NED', away:'SWE', venue:'NRG Stadium',           city:'Houston',      date:'2026-06-20', time:'12:00', roofed:true,  altitude:35   },
  { id:'F4', apiId:1489394, group:'F', home:'TUN', away:'JPN', venue:'Estadio BBVA',          city:'Monterrey',    date:'2026-06-20', time:'23:00', roofed:false, altitude:537  },
  { id:'F5', apiId:1539011, group:'F', home:'JPN', away:'SWE', venue:'AT&T Stadium',          city:'Dallas',       date:'2026-06-25', time:'18:00', roofed:true,  altitude:186  },
  { id:'F6', apiId:1489412, group:'F', home:'TUN', away:'NED', venue:'Arrowhead Stadium',     city:'Kansas City',  date:'2026-06-25', time:'18:00', roofed:false, altitude:290  },
  // GROUP G
  { id:'G1', apiId:1489377, group:'G', home:'BEL', away:'EGY', venue:'Lumen Field',           city:'Seattle',      date:'2026-06-15', time:'12:00', roofed:false, altitude:4    },
  { id:'G2', apiId:1489378, group:'G', home:'IRN', away:'NZL', venue:'SoFi Stadium',          city:'Los Angeles',  date:'2026-06-15', time:'18:00', roofed:true,  altitude:89   },
  { id:'G3', apiId:1489395, group:'G', home:'BEL', away:'IRN', venue:'SoFi Stadium',          city:'Los Angeles',  date:'2026-06-21', time:'12:00', roofed:true,  altitude:89   },
  { id:'G4', apiId:1489396, group:'G', home:'NZL', away:'EGY', venue:'BC Place',              city:'Vancouver',    date:'2026-06-21', time:'18:00', roofed:true,  altitude:5    },
  { id:'G5', apiId:1489414, group:'G', home:'EGY', away:'IRN', venue:'Lumen Field',           city:'Seattle',      date:'2026-06-26', time:'20:00', roofed:false, altitude:4    },
  { id:'G6', apiId:1489415, group:'G', home:'NZL', away:'BEL', venue:'BC Place',              city:'Vancouver',    date:'2026-06-26', time:'20:00', roofed:true,  altitude:5    },
  // GROUP H
  { id:'H1', apiId:1489380, group:'H', home:'ESP', away:'CPV', venue:'Mercedes-Benz Stadium', city:'Atlanta',      date:'2026-06-15', time:'12:00', roofed:true,  altitude:287  },
  { id:'H2', apiId:1489379, group:'H', home:'KSA', away:'URU', venue:'Hard Rock Stadium',     city:'Miami',        date:'2026-06-15', time:'18:00', roofed:false, altitude:2    },
  { id:'H3', apiId:1489397, group:'H', home:'ESP', away:'KSA', venue:'Mercedes-Benz Stadium', city:'Atlanta',      date:'2026-06-21', time:'12:00', roofed:true,  altitude:287  },
  { id:'H4', apiId:1489398, group:'H', home:'URU', away:'CPV', venue:'Hard Rock Stadium',     city:'Miami',        date:'2026-06-21', time:'18:00', roofed:false, altitude:2    },
  { id:'H5', apiId:1489417, group:'H', home:'URU', away:'ESP', venue:'Estadio Akron',         city:'Guadalajara',  date:'2026-06-26', time:'19:00', roofed:false, altitude:1566 },
  { id:'H6', apiId:1489413, group:'H', home:'CPV', away:'KSA', venue:'NRG Stadium',           city:'Houston',      date:'2026-06-26', time:'19:00', roofed:true,  altitude:35   },
  // GROUP I
  { id:'I1', apiId:1489383, group:'I', home:'FRA', away:'SEN', venue:'MetLife Stadium',       city:'New York',     date:'2026-06-16', time:'15:00', roofed:false, altitude:2    },
  { id:'I2', apiId:1539016, group:'I', home:'IRQ', away:'NOR', venue:'Gillette Stadium',      city:'Boston',       date:'2026-06-16', time:'18:00', roofed:false, altitude:24   },
  { id:'I3', apiId:1539017, group:'I', home:'FRA', away:'IRQ', venue:'Lincoln Financial Field',city:'Philadelphia', date:'2026-06-22', time:'17:00', roofed:false, altitude:11   },
  { id:'I4', apiId:1489401, group:'I', home:'NOR', away:'SEN', venue:'MetLife Stadium',       city:'New York',     date:'2026-06-22', time:'20:00', roofed:false, altitude:2    },
  { id:'I5', apiId:1539074, group:'I', home:'SEN', away:'IRQ', venue:'BMO Field',             city:'Toronto',      date:'2026-06-26', time:'15:00', roofed:false, altitude:76   },
  { id:'I6', apiId:1489416, group:'I', home:'NOR', away:'FRA', venue:'Gillette Stadium',      city:'Boston',       date:'2026-06-26', time:'15:00', roofed:false, altitude:24   },
  // GROUP J
  { id:'J1', apiId:1489381, group:'J', home:'ARG', away:'ALG', venue:'Arrowhead Stadium',     city:'Kansas City',  date:'2026-06-16', time:'20:00', roofed:false, altitude:290  },
  { id:'J2', apiId:1489382, group:'J', home:'AUT', away:'JOR', venue:"Levi's Stadium",        city:'Santa Clara',  date:'2026-06-16', time:'21:00', roofed:false, altitude:18   },
  { id:'J3', apiId:1489399, group:'J', home:'ARG', away:'AUT', venue:'AT&T Stadium',          city:'Dallas',       date:'2026-06-22', time:'12:00', roofed:true,  altitude:186  },
  { id:'J4', apiId:1489400, group:'J', home:'JOR', away:'ALG', venue:"Levi's Stadium",        city:'Santa Clara',  date:'2026-06-22', time:'20:00', roofed:false, altitude:18   },
  { id:'J5', apiId:1489418, group:'J', home:'ALG', away:'AUT', venue:'Arrowhead Stadium',     city:'Kansas City',  date:'2026-06-27', time:'21:00', roofed:false, altitude:290  },
  { id:'J6', apiId:1489421, group:'J', home:'JOR', away:'ARG', venue:'AT&T Stadium',          city:'Dallas',       date:'2026-06-27', time:'21:00', roofed:true,  altitude:186  },
  // GROUP K
  { id:'K1', apiId:1539003, group:'K', home:'POR', away:'COD', venue:'NRG Stadium',           city:'Houston',      date:'2026-06-17', time:'12:00', roofed:true,  altitude:35   },
  { id:'K2', apiId:1489386, group:'K', home:'UZB', away:'COL', venue:'Estadio Azteca',        city:'Mexico City',  date:'2026-06-17', time:'21:00', roofed:false, altitude:2240 },
  { id:'K3', apiId:1489404, group:'K', home:'POR', away:'UZB', venue:'NRG Stadium',           city:'Houston',      date:'2026-06-23', time:'12:00', roofed:true,  altitude:35   },
  { id:'K4', apiId:1539008, group:'K', home:'COL', away:'COD', venue:'Estadio Akron',         city:'Guadalajara',  date:'2026-06-23', time:'21:00', roofed:false, altitude:1566 },
  { id:'K5', apiId:1489419, group:'K', home:'COL', away:'POR', venue:'Hard Rock Stadium',     city:'Miami',        date:'2026-06-27', time:'19:30', roofed:false, altitude:2    },
  { id:'K6', apiId:1539013, group:'K', home:'COD', away:'UZB', venue:'Mercedes-Benz Stadium', city:'Atlanta',      date:'2026-06-27', time:'19:30', roofed:true,  altitude:287  },
  // GROUP L
  { id:'L1', apiId:1489384, group:'L', home:'ENG', away:'CRO', venue:'AT&T Stadium',          city:'Dallas',       date:'2026-06-17', time:'15:00', roofed:true,  altitude:186  },
  { id:'L2', apiId:1489385, group:'L', home:'GHA', away:'PAN', venue:'BMO Field',             city:'Toronto',      date:'2026-06-17', time:'19:00', roofed:false, altitude:76   },
  { id:'L3', apiId:1489402, group:'L', home:'ENG', away:'GHA', venue:'Gillette Stadium',      city:'Boston',       date:'2026-06-23', time:'16:00', roofed:false, altitude:24   },
  { id:'L4', apiId:1489403, group:'L', home:'PAN', away:'CRO', venue:'BMO Field',             city:'Toronto',      date:'2026-06-23', time:'19:00', roofed:false, altitude:76   },
  { id:'L5', apiId:1489420, group:'L', home:'CRO', away:'GHA', venue:'Lincoln Financial Field',city:'Philadelphia', date:'2026-06-27', time:'17:00', roofed:false, altitude:11   },
  { id:'L6', apiId:1489422, group:'L', home:'PAN', away:'ENG', venue:'MetLife Stadium',       city:'New York',     date:'2026-06-27', time:'17:00', roofed:false, altitude:2    },
]

export const CONDITIONS = [
  { key:'heat',     label:'Heat & humidity', short:'Heat',   icon:'☀' },
  { key:'pitch',    label:'Pitch quality',   short:'Pitch',  icon:'🏟' },
  { key:'altitude', label:'Altitude',        short:'Alt',    icon:'⛰' },
  { key:'travel',   label:'Travel & jet lag',short:'Travel', icon:'✈' },
  { key:'crowd',    label:'Crowd pressure',  short:'Crowd',  icon:'👥' },
  { key:'schedule', label:'Fixture load',    short:'Sched',  icon:'📅' },
]

export const GROUPS = ['A','B','C','D','E','F','G','H','I','J','K','L']

export const VENUE_COORDS = {
  'Mexico City':  { lat: 19.43, lon: -99.13 },
  'Guadalajara':  { lat: 20.66, lon: -103.35 },
  'Monterrey':    { lat: 25.67, lon: -100.31 },
  'Houston':      { lat: 29.69, lon: -95.41 },
  'Dallas':       { lat: 32.78, lon: -96.80 },
  'Atlanta':      { lat: 33.75, lon: -84.39 },
  'Miami':        { lat: 25.77, lon: -80.19 },
  'Los Angeles':  { lat: 34.05, lon: -118.24 },
  'Seattle':      { lat: 47.61, lon: -122.33 },
  'Santa Clara':  { lat: 37.40, lon: -121.97 },
  'New York':     { lat: 40.71, lon: -74.01 },
  'Boston':       { lat: 42.36, lon: -71.06 },
  'Philadelphia': { lat: 39.95, lon: -75.17 },
  'Kansas City':  { lat: 39.10, lon: -94.58 },
  'Toronto':      { lat: 43.65, lon: -79.38 },
  'Vancouver':    { lat: 49.28, lon: -123.12 },
  'London':       { lat: 51.51, lon: -0.13 },
  'Madrid':       { lat: 40.42, lon: -3.70 },
  'Paris':        { lat: 48.85, lon: 2.35 },
  'Berlin':       { lat: 52.52, lon: 13.40 },
  'Amsterdam':    { lat: 52.37, lon: 4.90 },
  'Brussels':     { lat: 50.85, lon: 4.35 },
  'Lisbon':       { lat: 38.72, lon: -9.14 },
  'Zagreb':       { lat: 45.81, lon: 15.98 },
  'Vienna':       { lat: 48.21, lon: 16.37 },
  'Bern':         { lat: 46.95, lon: 7.45 },
  'Prague':       { lat: 50.08, lon: 14.44 },
  'Stockholm':    { lat: 59.33, lon: 18.07 },
  'Oslo':         { lat: 59.91, lon: 10.75 },
  'Sarajevo':     { lat: 43.85, lon: 18.36 },
  'Tehran':       { lat: 35.69, lon: 51.39 },
  'Istanbul':     { lat: 41.01, lon: 28.95 },
  'Tunis':        { lat: 36.82, lon: 10.17 },
  'Buenos Aires': { lat: -34.61, lon: -58.38 },
  'Brasilia':     { lat: -15.78, lon: -47.93 },
  'Bogota':       { lat: 4.71,   lon: -74.07 },
  'Quito':        { lat: -0.23,  lon: -78.52 },
  'Asuncion':     { lat: -25.28, lon: -57.64 },
  'Montevideo':   { lat: -34.90, lon: -56.19 },
  'Rabat':        { lat: 34.02, lon: -6.85 },
  'Cairo':        { lat: 30.04, lon: 31.24 },
  'Algiers':      { lat: 36.74, lon: 3.06 },
  'Dakar':        { lat: 14.69, lon: -17.44 },
  'Abidjan':      { lat: 5.35,  lon: -4.01 },
  'Accra':        { lat: 5.56,  lon: -0.20 },
  'Kinshasa':     { lat: -4.32, lon: 15.32 },
  'Pretoria':     { lat: -25.75, lon: 28.19 },
  'Riyadh':       { lat: 24.69, lon: 46.72 },
  'Doha':         { lat: 25.29, lon: 51.53 },
  'Amman':        { lat: 31.96, lon: 35.95 },
  'Baghdad':      { lat: 33.34, lon: 44.40 },
  'Seoul':        { lat: 37.57, lon: 126.98 },
  'Tokyo':        { lat: 35.68, lon: 139.69 },
  'Tashkent':     { lat: 41.30, lon: 69.24 },
  'Wellington':   { lat: -41.29, lon: 174.78 },
  'Sydney':       { lat: -33.87, lon: 151.21 },
  'Port-au-Prince':{ lat: 18.54, lon: -72.34 },
  'Panama City':  { lat: 8.99,  lon: -79.52 },
  'Praia':        { lat: 14.93, lon: -23.51 },
  'Willemstad':   { lat: 12.12, lon: -68.93 },
  'Edinburgh':    { lat: 55.95, lon: -3.19 },
}

export const TEAM_HOME_CITY = {
  MEX: 'Mexico City', RSA: 'Pretoria',      KOR: 'Seoul',          CZE: 'Prague',
  CAN: 'Toronto',     BIH: 'Sarajevo',      QAT: 'Doha',           SUI: 'Bern',
  BRA: 'Brasilia',    MAR: 'Rabat',         HAI: 'Port-au-Prince', SCO: 'Edinburgh',
  USA: 'New York',    PAR: 'Asuncion',      AUS: 'Sydney',         TUR: 'Istanbul',
  GER: 'Berlin',      CUW: 'Willemstad',    CIV: 'Abidjan',        ECU: 'Quito',
  NED: 'Amsterdam',   JPN: 'Tokyo',         SWE: 'Stockholm',      TUN: 'Tunis',
  BEL: 'Brussels',    EGY: 'Cairo',         IRN: 'Tehran',         NZL: 'Wellington',
  ESP: 'Madrid',      CPV: 'Praia',         KSA: 'Riyadh',         URU: 'Montevideo',
  FRA: 'Paris',       SEN: 'Dakar',         IRQ: 'Baghdad',        NOR: 'Oslo',
  ARG: 'Buenos Aires',ALG: 'Algiers',       AUT: 'Vienna',         JOR: 'Amman',
  POR: 'Lisbon',      COD: 'Kinshasa',      UZB: 'Tashkent',       COL: 'Bogota',
  ENG: 'London',      CRO: 'Zagreb',        GHA: 'Accra',          PAN: 'Panama City',
}

export const VENUE_HEAT = {
  'Mexico City':  72,
  'Guadalajara':  78,
  'Monterrey':    88,
  'Houston':      92,
  'Dallas':       90,
  'Atlanta':      50,
  'Miami':        95,
  'Los Angeles':  55,
  'Seattle':      42,
  'Santa Clara':  48,
  'New York':     65,
  'Boston':       58,
  'Philadelphia': 68,
  'Kansas City':  82,
  'Toronto':      55,
  'Vancouver':    45,
}

export const VENUE_PITCH = {
  'Estadio Azteca':         55,
  'Estadio Akron':          70,
  'Estadio BBVA':           75,
  'Mercedes-Benz Stadium':  82,
  'BMO Field':              68,
  "Levi's Stadium":         72,
  'SoFi Stadium':           85,
  'BC Place':               78,
  'NRG Stadium':            78,
  'Gillette Stadium':       70,
  'AT&T Stadium':           88,
  'Hard Rock Stadium':      72,
  'Lumen Field':            74,
  'MetLife Stadium':        76,
  'Lincoln Financial Field':71,
  'Arrowhead Stadium':      73,
}
